### ISSUE TITLE
Files not being removed in deploy

### ISSUE THREAD

**Issue by digitalfuel** [mdyd-dev/pos-cli#317]
## Expected behavior
When deploying, files that is not in the local code base are removed from instance.

## Actual behavior
When I deploy I get the error `Validation failed: Slug has already been taken`. When there is only one file that has the path `https://df-video-profile-v0.staging.oregon.platform-os.com/video-profile/docs`

## Steps to reproduce the problem
I am not sure how or why this is happening. I did change the slug and files names a few times. I am also using a module template to generate part of the slug as seen below. Though if I change the template value from the current 'video-profile/docs' to says 'anotherPath/docs' then it works.

Current working front matter
```
---
converter: markdown
metadata:
  title: Installing the Video Profile Module
  description: This guide will help you install the Digital Fuel Video Profile Module.
slug: <%= &slug =%>/install
layout_name: modules/video_profile/docs
---
```
Replacement slug to get the error `Validation failed: Slug has already been taken`
`slug: <%= &slug =%>/docs`.

One navigating to https://df-video-profile-v0.staging.oregon.platform-os.com/video-profile/docs the page can be seen so something is there. But I cannot see any where in my code base where it is. I have looked for & search /docs and can find nothing that looks to conflict. The module is not that big with only 2 actual pages.

## Version

* pos-cli: 4.1.10
* node: v10.16.2
* os: windows 10
